# Runs the full lakehouse batch pipeline end to end with a final report.
import argparse
import importlib
import subprocess
import sys
import time
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from src.utils.connection import close_connection, get_postgres_connection
from src.utils.logger import get_logger
from src.utils.tracking import record_snapshot, track_stage

logger = get_logger(__name__)
console = Console()

BRONZE_DQ = sorted((REPO_ROOT / "tests" / "dq" / "bronze").glob("*.sql"))
SILVER_DQ = sorted((REPO_ROOT / "tests" / "dq" / "silver").glob("*.sql"))
GOLD_DQ = sorted((REPO_ROOT / "tests" / "dq" / "gold").glob("*.sql"))
SILVER_TABLES = (
    "customers",
    "drivers",
    "facilities",
    "routes",
    "trailers",
    "trucks",
    "loads",
    "trips",
    "fuel_purchases",
    "delivery_events",
    "maintenance_records",
    "safety_incidents",
)
GOLD_TABLES = (
    "dim_date",
    "dim_customer",
    "dim_driver",
    "dim_facility",
    "dim_route",
    "dim_trailer",
    "dim_truck",
    "fact_loads",
    "fact_trips",
    "fact_fuel_purchases",
    "fact_delivery_events",
    "fact_maintenance",
    "fact_safety_incidents",
)


# parses CLI flags for the pipeline run
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Lakehouse batch pipeline")
    parser.add_argument(
        "--batch-id",
        default="",
        help="Shared silver batch id, autogenerated when empty",
    )
    parser.add_argument(
        "--skip-extract",
        action="store_true",
        help="Reuse bronze as is, skip both extractors",
    )
    parser.add_argument(
        "--skip-quality",
        action="store_true",
        help="Skip DQ and GX gates, transform only",
    )
    return parser.parse_args()


# runs one extractor script as a subprocess, returning its exit code
def run_extractor(script: str) -> int:
    started = time.time()
    console.print(f"[bold blue]extract start[/] {script}")
    try:
        proc = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / script)],
            cwd=str(REPO_ROOT),
            check=False,
        )
        code = proc.returncode
    except Exception as exc:  # noqa: BLE001
        logger.error("extractor crashed script=%s error=%s", script, exc)
        code = 1
    console.print(
        f"[{'green' if code == 0 else 'red'}]extract done[/] "
        f"{script} exit={code} elapsed={time.time() - started:.1f}s"
    )
    return code


# runs mongo and databricks extracts side by side, failing on either
def stage_extract() -> None:
    with track_stage("extract"):
        with ThreadPoolExecutor(max_workers=2) as pool:
            codes = list(
                pool.map(run_extractor, ("run_mongo_job.py", "run_databricks_job.py"))
            )
        if any(code != 0 for code in codes):
            raise SystemExit(f"extract failed codes={codes}")


# runs every DQ loop check in a folder, raising on the first failure
def run_dq_checks(label: str, files: list[Path]) -> dict[str, int]:
    passed = 0
    with track_stage(label):
        for path in files:
            connection = get_postgres_connection()
            try:
                connection.autocommit = True
                with connection.cursor() as cur:
                    cur.execute(path.read_text(encoding="utf-8"))
                passed += 1
                console.print(f"  [green]PASS[/] {path.name}")
            except Exception as exc:  # noqa: BLE001
                console.print(f"  [red]FAIL[/] {path.name}: {exc}")
                raise SystemExit(f"DQ failed file={path.name} error={exc}")
            finally:
                close_connection(connection)
    return {"passed": passed, "failed": 0}


# runs one GX suite module, raising when its checkpoint fails
def run_gx(label: str, module: str) -> None:
    with track_stage(label):
        console.print(f"[bold blue]gx start[/] {label}")
        code = importlib.import_module(f"scripts.{module}").main()
        if code != 0:
            raise SystemExit(f"GX failed label={label}")
        console.print(f"[green]gx done[/] {label}")


# calls one master procedure with the shared batch id
def call_master(procedure: str, batch_id: str) -> None:
    connection = get_postgres_connection()
    try:
        connection.autocommit = True
        with connection.cursor() as cur:
            cur.execute(f"CALL {procedure}(%s)", (batch_id,))
    finally:
        close_connection(connection)


# transforms silver in dependency order with one shared batch id
def stage_silver(batch_id: str) -> None:
    with track_stage("silver"):
        for procedure in ("silver.load_mongo_all", "silver.load_databricks_all"):
            console.print(f"[bold blue]silver start[/] {procedure}")
            call_master(procedure, batch_id)
            console.print(f"[green]silver done[/] {procedure}")


# transforms gold in dependency order with one shared batch id
def stage_gold(batch_id: str) -> None:
    with track_stage("gold"):
        console.print("[bold blue]gold start[/] gold.load_gold_all")
        call_master("gold.load_gold_all", batch_id)
        console.print("[green]gold done[/] gold.load_gold_all")


# reads row counts for every silver table and its bronze source
def layer_counts() -> list[tuple[str, int, int]]:
    connection = get_postgres_connection()
    try:
        with connection.cursor() as cur:
            rows = []
            for table in SILVER_TABLES:
                cur.execute(f"SELECT COUNT(*) FROM bronze.{table}")
                bronze = cur.fetchone()[0]
                cur.execute(f"SELECT COUNT(*) FROM silver.{table}")
                silver = cur.fetchone()[0]
                rows.append((table, bronze, silver))
            return rows
    finally:
        close_connection(connection)


# reads the latest orchestrator outcomes for the report
def orchestrator_rows(batch_id: str) -> list[tuple]:
    connection = get_postgres_connection()
    try:
        with connection.cursor() as cur:
            cur.execute(
                "SELECT procedure_name, status, rows_in, rows_out, "
                "rows_rejected FROM silver.etl_logs "
                "WHERE batch_id = %s AND procedure_name IN "
                "('silver.load_mongo_all', 'silver.load_databricks_all') "
                "UNION ALL "
                "SELECT procedure_name, status, rows_in, rows_out, "
                "rows_rejected FROM gold.etl_logs "
                "WHERE batch_id = %s "
                "AND procedure_name = 'gold.load_gold_all' "
                "ORDER BY 1",
                (batch_id, batch_id),
            )
            return list(cur.fetchall())
    finally:
        close_connection(connection)


# prints the final pipeline report covering stages, layers, and quality
def print_report(
    batch_id: str, stages: list[tuple[str, str, float]], quality: dict[str, int]
) -> None:
    total = sum(elapsed for _, _, elapsed in stages)
    failed = sum(1 for _, status, _ in stages if status != "SUCCESS")
    console.print(
        Panel(
            f"batch [bold]{batch_id}[/] | "
            f"stages {len(stages) - failed}/{len(stages)} green | "
            f"total {total:.1f}s",
            title="Lakehouse pipeline report",
        )
    )
    stage_table = Table(title="Stages")
    stage_table.add_column("stage")
    stage_table.add_column("status")
    stage_table.add_column("secs", justify="right")
    for name, status, elapsed in stages:
        color = "green" if status == "SUCCESS" else "red"
        stage_table.add_row(name, f"[{color}]{status}[/]", f"{elapsed:.1f}")
    console.print(stage_table)
    count_table = Table(title="Layer row counts")
    count_table.add_column("table")
    count_table.add_column("bronze", justify="right")
    count_table.add_column("silver", justify="right")
    count_table.add_column("match", justify="center")
    total_bronze = total_silver = 0
    for table, bronze, silver in layer_counts():
        total_bronze += bronze
        total_silver += silver
        ok = bronze == silver
        count_table.add_row(
            table, f"{bronze:,}", f"{silver:,}", "[green]yes[/]" if ok else "[red]NO[/]"
        )
    count_table.add_row("total", f"{total_bronze:,}", f"{total_silver:,}", "")
    console.print(count_table)
    gold_table = Table(title="Gold row counts")
    gold_table.add_column("table")
    gold_table.add_column("rows", justify="right")
    connection = get_postgres_connection()
    try:
        with connection.cursor() as cur:
            for table in GOLD_TABLES:
                cur.execute(f"SELECT COUNT(*) FROM gold.{table}")
                gold_table.add_row(table, f"{cur.fetchone()[0]:,}")
    finally:
        close_connection(connection)
    console.print(gold_table)
    quality_table = Table(title="Quality gates")
    quality_table.add_column("gate")
    quality_table.add_column("passed", justify="right")
    quality_table.add_column("failed", justify="right")
    for gate in (
        "dq bronze",
        "gx bronze",
        "dq silver",
        "gx silver",
        "dq gold",
        "gx gold",
    ):
        passed = quality.get(gate, 0)
        quality_table.add_row(gate, str(passed), "0")
    console.print(quality_table)
    orch_table = Table(title="Master orchestrators")
    orch_table.add_column("procedure")
    orch_table.add_column("status")
    orch_table.add_column("in", justify="right")
    orch_table.add_column("out", justify="right")
    orch_table.add_column("rejected", justify="right")
    for name, status, rows_in, rows_out, rejected in orchestrator_rows(batch_id):
        color = "green" if status == "SUCCESS" else "red"
        orch_table.add_row(
            name,
            f"[{color}]{status}[/]",
            f"{rows_in:,}",
            f"{rows_out:,}",
            f"{rejected:,}",
        )
    console.print(orch_table)


# runs extract, gates, transform, gates, then reports
def main() -> int:
    args = parse_args()
    batch_id = args.batch_id or f"main_{datetime.now(UTC):%Y%m%d_%H%M%S}"
    quality: dict[str, int] = {}
    stages: list[tuple[str, str, float]] = []

    # tracks one stage, recording green or red with its duration
    def run_stage(name: str, func: Callable[..., None], *args: object) -> None:
        started = time.time()
        try:
            func(*args)
        except SystemExit:
            stages.append((name, "FAILED", time.time() - started))
            raise
        except Exception as exc:  # noqa: BLE001
            stages.append((name, "FAILED", time.time() - started))
            raise SystemExit(f"stage failed name={name} error={exc}")
        stages.append((name, "SUCCESS", time.time() - started))

    try:
        if args.skip_extract:
            console.print("[yellow]skip[/] extract, reusing bronze")
        else:
            run_stage("extract", stage_extract)
        if args.skip_quality:
            console.print("[yellow]skip[/] quality gates")
        else:
            run_stage("dq bronze", run_dq_checks, "dq-bronze", BRONZE_DQ)
            quality["dq bronze"] = len(BRONZE_DQ)
            run_stage("gx bronze", run_gx, "gx-bronze", "run_gx_bronze")
            quality["gx bronze"] = 12
        run_stage("silver", stage_silver, batch_id)
        if not args.skip_quality:
            run_stage("dq silver", run_dq_checks, "dq-silver", SILVER_DQ)
            quality["dq silver"] = len(SILVER_DQ)
            run_stage("gx silver", run_gx, "gx-silver", "run_gx_silver")
            quality["gx silver"] = 12
        run_stage("gold", stage_gold, batch_id)
        if not args.skip_quality:
            run_stage("dq gold", run_dq_checks, "dq-gold", GOLD_DQ)
            quality["dq gold"] = len(GOLD_DQ)
            run_stage("gx gold", run_gx, "gx-gold", "run_gx_gold")
            quality["gx gold"] = 13
        record_snapshot()
    finally:
        print_report(batch_id, stages, quality)
    failed = sum(1 for _, status, _ in stages if status != "SUCCESS")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
