[project]
name = "lakehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks-sdk>=0.146.0",
    "databricks-sql-connector>=4.6.0",
    "delta-spark>=4.4.0",
    "ipykernel>=7.4.0",
    "jupyter-client>=8.10.0",
    "matplotlib>=3.11.2",
    "nbclient>=0.11.0",
    "nbformat>=5.11.1",
    "pandas>=3.0.6",
    "psycopg[binary]>=3.3.6",
    "pyarrow>=25.0.1",
    "pymongo>=4.18.2",
    "pyspark>=4.2.0",
    "python-dotenv>=1.2.4",
    "rich>=15.0.0",
    "seaborn>=0.13.2",
]
