# Calls the databricks silver master procedure and prints the audit summary.
import argparse
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rich.console import Console
from rich.table import Table

from src.utils.connection import close_connection, get_postgres_connection
from src.utils.tracking import track_stage

PROCEDURE = "silver.load_databricks_all"


# prints one clean end summary from the audit rows of this batch
def print_summary(batch_id: str, elapsed: float, code: int) -> None:
    try:
        connection = get_postgres_connection()
    except Exception as exc:  # noqa: BLE001
        print(f"summary unavailable: {exc}")
        return
    try:
        with connection.cursor() as cur:
            cur.execute(
                "SELECT procedure_name, status, rows_in, rows_out, "
                "rows_rejected FROM silver.etl_logs WHERE batch_id = %s "
                "ORDER BY finished_at",
                (batch_id,),
            )
            rows = cur.fetchall()
    finally:
        close_connection(connection)
    failed = sum(1 for row in rows if row[1] != "SUCCESS")
    table = Table(
        title=f"databricks silver done: exit={code} "
        f"elapsed={elapsed:.1f}s failed={failed}"
    )
    table.add_column("procedure")
    table.add_column("status")
    table.add_column("in", justify="right")
    table.add_column("out", justify="right")
    table.add_column("rejected", justify="right")
    for name, status, rows_in, rows_out, rejected in rows:
        table.add_row(name, status, f"{rows_in:,}", f"{rows_out:,}", f"{rejected:,}")
    Console().print(table)


# calls the databricks master with one shared batch id
def main() -> int:
    parser = argparse.ArgumentParser(description="Databricks silver master run")
    parser.add_argument(
        "--batch-id", default="", help="Shared batch id, autogenerated when empty"
    )
    batch_id = (
        parser.parse_args().batch_id or f"databricks_{datetime.now(UTC):%Y%m%d_%H%M%S}"
    )
    started = time.time()
    with track_stage("silver_databricks"):
        connection = get_postgres_connection()
        try:
            connection.autocommit = True
            with connection.cursor() as cur:
                cur.execute(f"CALL {PROCEDURE}(%s)", (batch_id,))
        finally:
            close_connection(connection)
        print_summary(batch_id, time.time() - started, 0)
        return 0


if __name__ == "__main__":
    sys.exit(main())
